jet/FsKafka

- src/Confluent.Kafka.FSharp/ConfluentKafka.fs
- tests/Confluent.Kafka.FSharp.Tests/Tests.fs
Await `handle` before storing new offsets
If we don't do this then we run the risk of committing offsets for
messages that may not have been handled yet. It exposes consumers to the
possibility of consuming messages more than once, but makes this wrapper
behave closer to how Kafunk does in terms of at-least-once semantics.
Addresses one of the concerns raised in #9.
> Fix eager offset storage bug

- src/Confluent.Kafka.FSharp/ConfluentKafka.fs
Using `Object.ToString()` is not reliable enough as this caused runtime
issues when called from across assembly boundaries. For example, this
function returned "confluent.kafka.config+producer+compression" when
passed `Confluent.Kafka.Config.Producer.Compression.None`. Using
reflection should yield more predictable results.
> Use reflection to get config DU case labels

- CHANGELOG.md
- README.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
- src/Jet.ConfluentKafka.FSharp/Jet.ConfluentKafka.FSharp.fsproj
Syncs with latest `Confluent.Kafka` lib. TL;DR
- they didn't break much API-wise that overlaps with us
- CK 1.0.0-RC1 still targets the same rdkafka 0.11.6-PRE2 so this doesn't prove all that much
> Target Confluent.Kafka 1.0.0-RC1

- CHANGELOG.md
- src/Jet.ConfluentKafka.FSharp/Jet.ConfluentKafka.FSharp.fsproj
Update to use `Confluent.Kafka 1.0.0-RC2`, which targets `librdkafka 1.0.0`
Also addresses #22, pinning to specific tested versions for consistency
> Target CK 1.0.0rc2+rdkafka 1.0.0

- CHANGELOG.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
- src/Jet.ConfluentKafka.FSharp/Jet.ConfluentKafka.FSharp.fsproj
- Update to CK1.0 RC3
- no underlying `rdkafka` updated associated with same
- use intrinsic `CompressionType` added in this release
> Target Confluent.Kafka 1.0.0-RC3; use CompressionType

- RELEASE_NOTES.md
- src/Confluent.Kafka.FSharp/ConfluentKafka.fs
Confluent throws an error if the debug flags array is empty. This PR updates `Config.debug` to ignore debug flags if the list is empty.
> Correctly handle config with empty debug flags

- CHANGELOG.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
This is the result of a read-and-review as I'm using this in a client template. I've applied the following:
- _intentional minor breaking changes_ to remove arbitrary deviations from `Confluent.Kafka` defaults:
- `offsetCommitInterval` - the frequency of commits of consumer offsets increases to 5s to align with CK default (was 10s for historical reasons)
- `fetchMinBytes` default is now 1B (was 10B for historical reasons)
- adding information as to how the settings used relate to documented `Confluent.Kafka` default values
- removed egregious setting of CK Config values to `null`
- exposed an `Inner` on Producer/Consumer to enable custom client logic without having to fork
- F# syntax conventions - no egregious `val` usage, no curried `member`s
> Pre 1.0 API cleanup

- CHANGELOG.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
- tests/Jet.ConfluentKafka.FSharp.Integration/Integration.fs
Splits the Batch production logic into a separated types and changes some defaults in the interests of safety/reducing ambiguity:
- sets default `maxInFlightRequests` to `1` (instead of `1_000_000`), requiring opting in to the potentially reordering behavior implied by the default. Per Kafka, The Definitive Guide:
> if guaranteeing order is critical, we recommend setting in.flight.requests.per.session=1 to make sure that while a batch of messages is retrying, additional messages will not be sent
- increases batch production linger from 10ms to 100ms (`Confluent.Kafka` default value, makes sense)
- provides a mechanism to avoid logging messages from the `InFlightMessageCounter`:
```
.MinimumLevel.Override(Jet.ConfluentKafka.FSharp.Constants.messageCounterSourceContext, …
```
> Split Batching impls out to own types; make defaults less surprising

- CHANGELOG.md
- README.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
provides a mechanism to avoid logging messages from the `InFlightMessageCounter`:
```
.MinimumLevel.Override(Jet.ConfluentKafka.FSharp.Constants.messageCounterSourceContext, Serilog.Events.LogEventLevel.Warning )
```
> Add way to filter InFlightMessageCounter re #31

- CHANGELOG.md
- Jet.ConfluentKafka.FSharp.sln
- src/Propulsion.Kafka/Infrastructure.fs
- src/Propulsion.Kafka/KafkaPropulsion.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion/Infrastructure.fs
- src/Propulsion/Propulsion.fs
- src/Propulsion/Propulsion.fsproj
- tests/Jet.ConfluentKafka.FSharp.Integration/Jet.ConfluentKafka.FSharp.Integration.fsproj
- tests/Jet.ConfluentKafka.FSharp.Integration/ParallelConsumerIntegration.fs
In preparation for adding a StreamedConsumer, this PR:
- moves generic parallelism-related logic out of `Jet.ConfluentKafka.FSharp` into `Propulsion`
- moves `ParallelConsumer`'s implementation into `Propulsion.Kafka`
> Split ParallelConsumer out to Propulsion+Propulsion.Kafka

- CHANGELOG.md
- Jet.ConfluentKafka.FSharp.sln
- build.proj
- src/Propulsion.Kafka/Consumers.fs
- src/Propulsion.Kafka/Producers.fs
- src/Propulsion.Kafka/Propulsion.Kafka.fsproj
- src/Propulsion/Infrastructure.fs
- src/Propulsion/Ingestion.fs
- src/Propulsion/Projector.fs
- src/Propulsion/Propulsion.fsproj
- src/Propulsion/Streams.fs
- tests/Propulsion.Tests/ProgressTests.fs
- tests/Propulsion.Tests/Propulsion.Tests.fsproj
- tests/Propulsion.Tests/StreamStateTests.fs
Implements components to enable pipelines that accommodate:
- merging and buffering by stream
- having a separated `Ingester` task to manage the buffering and asynchronous Document parsing necessitated by the push-pull model of the CosmosDb ChangeFeedProcessor
- writing progress asynchronously
The design and implementation is intentionally in line with that used in the `ParallelConsumer`, in order that it can slot into the same `ConsumerPipeline` for Kafka (and similar arrangements for CosmosDb etc)
> Add StreamsProducer + StreamsConsumer

- CHANGELOG.md
- src/Propulsion.Kafka/Producers.fs
- src/Propulsion/Parallel.fs
- src/Propulsion/Propulsion.fsproj
Caters for cases where one needs:
- Range-driven Ingestion (with async progress checkpointing), e.g. from CosmosDb's ChangeFeedProcessor
- the ability to produce messages to Kafka based on the inputs
But does not need:
- ordering or deduplication as `Streams` based algorithms provide
- Stream-level isolation
- Coalescing of events within a stream
> Add ParallelProducer

- CHANGELOG.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
- Update xmldoc, make one piece of defaulting less surprising. Not urgent so no urgency to push unless someone has a reason. (will likely roll in with an update to a newer CK version)
- Fix unintentional `Nullable` for `partitioner`
> Fix MessageMaxBytes defaulting

- CHANGELOG.md
- README.md
- src/Jet.ConfluentKafka.FSharp/ConfluentKafka.fs
- src/Jet.ConfluentKafka.FSharp/Jet.ConfluentKafka.FSharp.fsproj
> Target Confluent.Kafka 1.2.0

- README.md
What can be wrong (just complaining, no so important):
- the  need to `open Confluent.Kafka`, longer one liner
- Replacing 'ProduceAsync` with `Produce` may appear for more proper-modern-expected API
- need to create logger, allow for default null logger
> minimal example

- CHANGELOG.md
- src/FsKafka/ConfluentKafka.fs
- tests/FsKafka.Integration/Integration.fs
The `broker : Uri` arg in the Producer and Consumer config wrappers currently constrain the `bootstrapServers` passed to a single entry.
This obscures a core function of an idiomatic Kafka Client for a debatable reason
There is currently a workaround (which I didnt realize in advance of implementing this 😊) - supply a dummy value for `broker` and then stuff in a custom `bootstrapServers` value via `custom`
I may consider deferring the merging of this until 2.0.0 depending on what folks think
If anyone has any insights like e.g. telling me that in practice `bootstrapServers` are never usefully >1 therefore this makes no sense, let me know too!
This will also flow through to the parallel implementation contained in https://github.com/jet/propulsion/tree/master/src/Propulsion.Kafka0
> Change broker to bootstrapServers

- CHANGELOG.md
- src/FsKafka/ConfluentKafka.fs
Derived from code/requirements by @luo4neck @eglyph
- Provides ability to optionally add headers to messages in `ProduceAsync`
- Exposes a `ProduceAsync` overload
- Threads through cancellation
> Add ProduceAsync overloads for headers, raw messages

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/ConfluentKafkaShims.fs
- src/FsKafka0/FsKafka.fs
- tests/FsKafka.Integration/Integration.fs
- The longstanding default for autoOffsetReset for FsKafka has always been `earliest`, which is a safe default, but is not the Confluent.Kafka one (which is Latest).
This PR removes that defaulting in order to force a deliberate choice on the part of the user.
- Exposes `requestTimeout` on `KafkaProducerConfig.Create`
cc @wantastic84 @swrhim
> Add/Change KafkaConsumer/ProducerConfig autoOffsetReset, requestTimeout

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
- tests/FsKafka.Integration/Integration.fs
Prompted by Confluent.Kafka changing the default linger from 0.5 ms to 5 ms in v 1.5.0 (see #65), this revises the configuration API to force specification of a linger value in all cases.
- There is one sensitive API which `Propulsion.Kafka` uses: `KafkaProducerConfig.Create`, which I've `Obsolete`d
- The other change (CreateWithConfigOverrides -> Create and associated removal of arguments) is safe as it is only in consumer code
resolves #65
> Encapsulate linger/batching semantics

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/ConfluentKafkaShims.fs
- src/FsKafka0/FsKafka.fs
[librdkafka 1.5.0](https://github.com/edenhill/librdkafka/releases/tag/v1.5.0) changes the default value of `allow.auto.create.topics` from `true` to `false`
This exposes a clean way to override the setting
🤔 should it default to `true` if unspecified?
> Implement KafkaProducerConfig.allowAutoCreateTopics

- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
- tests/FsKafka.Integration/Integration.fs
- tests/FsKafka0.Integration/FsKafka0.Integration.fsproj
Inhibits triggering of Confluent.Kafka 1.x functionality whereby a Consumer can be forcibly closed due to being considered due to a combination of:
- handlers are stalled for long enough that it's in the `AwaitThreshold` phase of the loop for a sustained period longer than the `max.pol.interval.ms`
- `AwaitThreshold` does not call `.Consume`
The problem manifests as:
1. A warning being logged: `Consuming... "[thrd:main]: Application maximum poll interval (300000ms) exceeded by 491ms (adjust max.poll.interval.ms for long-running message processing): leaving group" level=Warning name="TheServiceName#consumer-1" facility="MAXPOLL"`
which can occur if the nature of the handler progress is such that the consumer is stuck in the loop for > 5 mins (the default `max.poll.interval.ms`)
2. A` …
> Use Pause/Resume when pausing polling

- tests/FsKafka.Integration/Integration.fs
Adding FsKafka.Monitor in one of the integration tests.
Took out the test from T2 and made T4 to be more readable
> Adding FsKafka.Monitor to integration tests

- CHANGELOG.md
- README.md
- src/FsKafka/Monitor.fs
- tests/FsKafka.Integration/Integration.fs
This change makes the monitor run disposable so that the thread can be terminated properly.
I was thinking about providing an option to make the loop terminate after x number of fail count, but that PR will follow later as needed.
Resolves #74
> Add mechanism to tear down KafkaMonitor threads

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
Although any uncaught exception within the consumer's batch processing loop will bubble up to the client, it is helpful to log the exception in case the client does not properly handle/log it. 
FsKafka simply logs the fully qualified name of the exception along with the exception message, but the full stacktrace and such needs to be logged from the client side.
> Adding exception logging for consumer's batch processing loop

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
There was a memory leak in the tail recursion loop `rec loop` where disposables are not being disposed until the recursion terminates. The fix was done to replace the recursion with while loop.
To illustrate the issue, here is an example for memory leak in tail recursion:
```
let myDisposer name =
{ new System.IDisposable
with member this.Dispose() = printfn "disposing %s" name }
let mutable count = 3
let rec loop () = async {
if count > 0 then
use _ = myDisposer "foo"
count <- count - 1
printfn "sleeping for 2 sec for count %d" count
do! Async.Sleep(2000)
return! loop()
}
loop() |> Async.RunSynchronously
```
In this case, disposable will not be disposed until the tail recursion terminates. Thus the outcome will be:
```
sleeping for 2 sec for count 3
sleeping for 2 sec for count 2 …
```
> Fix memory leak in tail recursion

- CHANGELOG.md
- src/FsKafka/FsKafka.fsproj
No breaking changes, Just pinning a dependency on 1.5.2, which brings various bugfixes
> Target Confluent.Kafka / librdkafka 1.5.2

- CHANGELOG.md
- README.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
- tests/FsKafka.Integration/Integration.fs
The current API does not provide a clear way to have a service cleanly shut down in response to the faulting of one of a set of consumers.
This PR extends the API to provide such a mechanism
> Add AwaitWithStopOnCancellation

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka0/FsKafka.fs
- Add type annotations to custom config helpers
- Expose `maxMessageBytes` on the `ProducerConfig` directly
> Add ProducerConfig maxMessageBytes

- Directory.Build.props
- README.md
- azure-pipelines.yml
- src/FsKafka/FsKafka.fsproj
- tests/FsKafka.Integration/FsKafka.Integration.fsproj
- tests/FsKafka.Integration/Integration.fs
This should simplify future releases/tests having to support only netstandard 2.0, and simplify upgrading to future versions of Confluent Kafka.
> Remove targeting for Net 461

- CHANGELOG.md
- src/FsKafka/FsKafka.fs
- src/FsKafka/FsKafka.fsproj
- Remove `AwaitThreshold`
- Target CK 1.7.0 and librdkafka 1.7.0
> Finish up roadmap to 1.7.0
